Internal Server Error: /project/ajax/getDetailRecommendations/
Traceback (most recent call last):
  File "/home/siew/venvs/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/siew/venvs/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/siew/venvs/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/siew/djmatch/src/project/views.py", line 34, in AjaxGetDetailRecommendations
    return JsonResponse({"keywords" : list(k)},status=200)
UnboundLocalError: local variable 'k' referenced before assignment
"GET /project/ajax/getDetailRecommendations/?id=25 HTTP/1.1" 500 19721
Internal Server Error: /project/ajax/getDetailRecommendations/
Traceback (most recent call last):
  File "/home/siew/venvs/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/siew/venvs/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/siew/venvs/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/siew/djmatch/src/project/views.py", line 34, in AjaxGetDetailRecommendations
    return JsonResponse({"keywords" : list(k)},status=200)
UnboundLocalError: local variable 'k' referenced before assignment
"GET /project/ajax/getDetailRecommendations/?id=25 HTTP/1.1" 500 19721
